apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-guestbook
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://gcr.io/heptio-images/ks-guestbook-demo
    chart: helm-guestbook
    targetRevision: 4.0.1
    helm:
      values: |
        pushgateway:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true