apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress
spec:
  project: default
  source:
    chart: ingress
    repoURL: https://charts.konghq.com
    targetRevision: 0.18.0
  destination:
    name: "in-cluster"
    namespace: default